arch = [
    # steam
    "steam",
    "ttf-liberation",
    "wqy-zenhei",
    "lib32-fontconfig",

    # osrs
    "bolt-launcher",
    "jre-openjdk",

    # heroic 
    "heroic-games-launcher-bin",
    # wine dependency hell
    "wine-staging",
    "winetricks",
    "giflib",
    "lib32-giflib",
    "libpng",
    "lib32-libpng",
    "libldap",
    "lib32-libldap",
    "gnutls",
    "lib32-gnutls",
    "mpg123",
    "lib32-mpg123",
    "openal",
    "lib32-openal",
    "v4l-utils",
    "lib32-v4l-utils",
    "libpulse",
    "lib32-libpulse",
    "alsa-plugins",
    "lib32-alsa-plugins",
    "alsa-lib",
    "lib32-alsa-lib",
    "libjpeg-turbo",
    "lib32-libjpeg-turbo",
    "libxcomposite",
    "lib32-libxcomposite",
    "libxinerama",
    "lib32-libxinerama",
    "ncurses",
    "lib32-ncurses",
    "opencl-icd-loader",
    "lib32-ocl-icd",
    "libxslt",
    "lib32-libxslt",
    "libva",
    "lib32-libva",
    "gtk3",
    "lib32-gtk3",
    "gst-plugins-base-libs",
    "lib32-gst-plugins-base-libs",
    "vulkan-icd-loader",
    "lib32-vulkan-icd-loader",
    "cups",
    "samba",
    "dosbox"
]
