arch_package_manager = "yay"
hostname_groups_enabled = true

[hostname_groups]
pc = ["base", "nvidia", "audio", "development", "apps", "wayland", "games"]
laptop = ["base", "base-laptop", "amd", "audio", "development", "apps", "wayland", "games"]
